/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 05 14:38:29 AMT 2018
 */

package cal;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.fail;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true) 
public class Cal_ESTest extends Cal_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Cal cal0 = new Cal();
      char[] charArray0 = new char[0];
      Cal.string = charArray0;
      char[] charArray1 = new char[8];
      charArray1[0] = 'K';
      charArray1[1] = '}';
      charArray1[2] = '~';
      charArray1[3] = '8';
      charArray1[4] = 'h';
      charArray1[5] = '`';
      charArray1[6] = '<';
      charArray1[7] = ')';
      Cal.string = charArray1;
      cal0.isLeap(1800);
      cal0.jan1(1800);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Cal cal0 = new Cal();
      cal0.cal(1601, 0);
      int[] intArray0 = new int[0];
      Cal.mon = intArray0;
      Cal.dayw = "gU7t4Qhomo{OP]mH";
      cal0.isLeap((-2635));
      cal0.jan1(9999);
      // Undeclared exception!
      cal0.cal(9999, 3576);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Cal cal0 = new Cal();
      int int0 = 2;
      int int1 = (-876);
      cal0.cal((-876), (-876));
      String[] stringArray0 = new String[0];
      Cal.dayw = "";
      Cal.smon = stringArray0;
      // Undeclared exception!
      try { 
        cal0.firstOfMonth(2, 2);
       //  fail("Expecting exception: ArrayIndexOutOfBoundsException");
       // Unstable assertion
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("cal.Cal", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Cal cal0 = new Cal();
      String[] stringArray0 = new String[4];
      char[] charArray0 = new char[1];
      charArray0[0] = '$';
      Cal.string = charArray0;
      Cal.smon = stringArray0;
      stringArray0[0] = "0";
      stringArray0[1] = "0";
      stringArray0[2] = "0";
      stringArray0[3] = "0";
      Cal.main(stringArray0);
      Cal.dayw = "0";
      cal0.firstOfMonth((-1), 1594);
      // Undeclared exception!
      try { 
        cal0.numberOfDays((-1), 2);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("cal.Cal", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Cal cal0 = new Cal();
      String[] stringArray0 = new String[1];
      stringArray0[0] = "";
      Cal.smon = stringArray0;
      cal0.isLeap(1793);
      cal0.isLeap(1793);
      cal0.cal((-961), (-961));
      cal0.cal((-653), 1);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      String[] stringArray0 = new String[2];
      stringArray0[0] = "M||-bU";
      stringArray0[1] = ";mx:";
      Cal.main(stringArray0);
      Cal cal0 = new Cal();
      // Undeclared exception!
      try { 
        cal0.firstOfMonth(3909, 1752);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("cal.Cal", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Cal cal0 = new Cal();
      int[] intArray0 = new int[1];
      intArray0[0] = (-1);
      Cal.mon = intArray0;
      cal0.isLeap(0);
      cal0.firstOfMonth(0, 5576);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String[] stringArray0 = new String[0];
      // Undeclared exception!
      try { 
        Cal.main(stringArray0);
       //  fail("Expecting exception: ArrayIndexOutOfBoundsException");
       // Unstable assertion
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 5
         //
         verifyException("cal.Cal", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Cal cal0 = new Cal();
      Cal.dayw = "";
      cal0.cal(0, 0);
      Cal.dayw = null;
      cal0.isLeap(275);
      cal0.firstOfMonth(0, 1055);
      cal0.isLeap(8);
      // Undeclared exception!
      try { 
        cal0.numberOfDays(1055, 1800);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1055
         //
         verifyException("cal.Cal", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Cal cal0 = new Cal();
      cal0.isLeap(0);
      cal0.numberOfDays(0, (-1));
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Cal cal0 = new Cal();
      char[] charArray0 = new char[1];
      charArray0[0] = '\'';
      Cal.string = charArray0;
      Cal.dayw = "Cal: %s: ano invalido.\n";
      Cal.dayw = "Cal: %s: ano invalido.\n";
      Cal.dayw = "Cal: %s: ano invalido.\n";
      // Undeclared exception!
      try { 
        cal0.firstOfMonth(1728, 3925);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1
         //
         verifyException("cal.Cal", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Cal cal0 = new Cal();
      // Undeclared exception!
      try { 
        Cal.main((String[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("cal.Cal", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Cal cal0 = new Cal();
      cal0.firstOfMonth((-757), (-757));
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Cal cal0 = new Cal();
      String[] stringArray0 = new String[2];
      stringArray0[0] = "&kA%;R<$cHv_G~";
      stringArray0[1] = "";
      Cal.main(stringArray0);
      cal0.firstOfMonth((-676), (-676));
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Cal cal0 = new Cal();
      String string0 = "       1  2 14 15 16\n17 18 19 20 21 22 23\n24 25 26 27 28 29 30";
      int[] intArray0 = new int[3];
      intArray0[0] = 0;
      intArray0[1] = 4051;
      int int0 = (-1473);
      intArray0[2] = (-1473);
      Cal.mon = intArray0;
      Cal.dayw = "       1  2 14 15 16\n17 18 19 20 21 22 23\n24 25 26 27 28 29 30";
      cal0.firstOfMonth(0, 0);
      // Undeclared exception!
      try { 
        cal0.numberOfDays(4, 0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 4
         //
         verifyException("cal.Cal", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Cal cal0 = new Cal();
      int[] intArray0 = new int[4];
      intArray0[0] = 1072;
      intArray0[1] = 743;
      char[] charArray0 = new char[8];
      charArray0[0] = 'Z';
      charArray0[1] = 'D';
      charArray0[2] = 'A';
      charArray0[3] = 'W';
      charArray0[4] = '/';
      charArray0[5] = 'O';
      charArray0[6] = 'm';
      charArray0[7] = 'G';
      Cal.string = charArray0;
      intArray0[2] = (-636);
      Cal.mon = intArray0;
      cal0.cal(1566, 1072);
      intArray0[3] = 0;
      Cal.mon = intArray0;
      cal0.jan1(1692);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Cal cal0 = new Cal();
      char[] charArray0 = new char[3];
      cal0.cal((-419), (-3918));
      charArray0[0] = 'u';
      charArray0[1] = 'M';
      charArray0[2] = 'F';
      Cal.dayw = "Mar\uFFFDo";
      Cal.string = charArray0;
      cal0.firstOfMonth(0, 0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Cal cal0 = new Cal();
      cal0.jan1(0);
      String[] stringArray0 = new String[3];
      stringArray0[0] = "";
      stringArray0[1] = "";
      stringArray0[2] = "3@MHjhz";
      Cal.main(stringArray0);
      // Undeclared exception!
      try { 
        cal0.numberOfDays(638, 0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 638
         //
         verifyException("cal.Cal", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Cal cal0 = new Cal();
      int int0 = 31;
      // Undeclared exception!
      try { 
        cal0.numberOfDays((-1), 31);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("cal.Cal", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Cal cal0 = new Cal();
      cal0.firstOfMonth((-1), 0);
      int int0 = (-2082);
      cal0.cal((-2082), (-2082));
      int int1 = 288;
      // Undeclared exception!
      try { 
        cal0.firstOfMonth(288, 0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 4
         //
         verifyException("cal.Cal", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      String[] stringArray0 = new String[6];
      stringArray0[0] = "&gu";
      stringArray0[1] = "[HSOZ0";
      stringArray0[2] = "";
      stringArray0[3] = "s|jX'CUx!& sT";
      stringArray0[4] = "k#%:L}t";
      stringArray0[5] = ")";
      Cal.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Cal cal0 = new Cal();
      char[] charArray0 = new char[0];
      cal0.cal(0, 30);
      Cal.string = charArray0;
      Cal.string = charArray0;
      cal0.jan1(1);
      cal0.cal(1, 1835);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Cal cal0 = new Cal();
      String[] stringArray0 = new String[6];
      stringArray0[0] = "]]z!K/_7ua*z";
      stringArray0[1] = "9BrRYQ";
      stringArray0[2] = "I!vgpi8GG";
      stringArray0[3] = "";
      stringArray0[4] = "";
      stringArray0[5] = "~Z|d{|G+ vW";
      Cal.smon = stringArray0;
      String string0 = cal0.cal(141, 1701);
      assertNotNull(string0);
  }
}
